{% set name = "sphinx-autoapi" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 842c0a8f49c824803f7edee31cb1cabd5001a987553bec7b4681283ec9e47d4a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astroid >=2.4
    - pyyaml
    - sphinx >=3.0
    - sphinxcontrib-golangdomain
    - sphinxcontrib-dotnetdomain
    - unidecode

test:
  requires:
    - pydocstyle
    - salvus_mesher_lite  # [osx]
  imports:
    - autoapi

about:
  home: http://github.com/rtfd/sphinx-autoapi
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.mit
  summary: Sphinx auto API documentation generator
  doc_url: http://sphinx-autoapi.readthedocs.io/en/latest/
  dev_url: https://github.com/rtfd/sphinx-autoapi

extra:
  recipe-maintainers:
    - CurtLH
